---
images:
  names:
    initServer: alpine:3.15
    server: tommartensen/tfui:0.0.1
  pullPolicy: Always

server:
  containerPort: 8080
  user:
    uid: 65534
    gid: 65534
  deploy:
    replicas: 1
    maxUnavailable: 1
  ingress:
    enabled: false
    host: ''
    ingressClassName: ''
    annotations: {}
    tls: []
  persistence:
    enabled: false
    storageClass: ''
    capacity: ''
  applicationToken: ''
