---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.server.deploy.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.server.deploy.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
{{- if .Values.server.persistence.enabled }}
      initContainers:
        - image: {{ .Values.images.names.initServer }}
          name: init-chmod-data
          command: ["/bin/chown", "-R", "{{ .Values.server.user.uid }}:{{ .Values.server.user.gid }}", "/plans"]
          volumeMounts:
          - mountPath: /plans
            name: {{ .Release.Name }}-volume
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.images.names.server }}
        imagePullPolicy: {{ .Values.images.pullPolicy}}
        ports:
        - name: http
          containerPort: {{ .Values.server.containerPort }}
        volumeMounts:
        - name: {{ .Release.Name }}-volume
          mountPath: /plans
{{- if .Values.server.applicationToken }}
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-application-token
{{- end }}
      volumes:
        - name: {{ .Release.Name }}-volume
{{- if .Values.server.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-claim
{{- else }}
          emptyDir: {}
{{- end -}}
