{{- if .Values.server.applicationToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-application-token
  namespace: {{ .Release.Namespace }}
data:
  APPLICATION_TOKEN: {{ .Values.server.applicationToken | b64enc }}
{{- end -}}
